### ISSUE TITLE
min.sample argument in preDA function

### ISSUE THREAD

**Issue by Morgan-Bragg** [Russel88/DAtest#10]
Hello,

I have a question about the min.sample argument in the preDA function. I am fairly new to using DAtest and was wondering if there is a specific amount of minimum samples that the feature is present in that is considered "good"? I was going through the supplementary script attached to your paper [Russel et al. 2018 DAtest: a framework for choosing differential abundance or expression method] and you chose these parameters for the preDA function: preDA(Sub, min.samples = 4, min.reads = 100). Why exactly were those parameters chosen? Just trying to get an understanding so I can apply it to my own data.

Thank you so much for your help!!
Morgan

**Comment by Russel88** [comment]
Hi Morgan,

I do not know of a "correct" way to choose the cutoff, but there are some things to consider when choosing these parameters. First, a feature should have a count > 0 at least in some samples. If it's only found in very few samples you can't really do any statistics anyway. Second, the counts should not be too low, because noise will have a large effect on fold changes with counts close to zero. The challenge then is to choose these parameters such that we remove the features where we don't have enough information, but keep the rare ones that are of potential interest. This choice also depends on your experimental design and number of samples.

Sorry about the late answer. Hope you still find it useful.

Cheers,
Jakob
