### ISSUE TITLE
Clarification on terminology of "raw counts" vs. "absolute abundance"

### ISSUE THREAD

**Issue by teyden** [Russel88/DAtest#14]
Hi,

I saw that it is recommended we provide either (1) raw counts & compositional data, or (2) externally normalized or absolute abundance data. 

Perhaps I have been using the terminology differently this entire time but my understanding is that raw counts is equivalent to the absolute abundances. Particularly, for microbiome data, where each sample represents a snapshot of the entire microbiome, actual "absolute abundance" is technically impossible. I have come to understand that the raw counts were considered the absolute abundances of the sample, and that relative abundance data represents proportion-normalized abundances. 

Could I please get clarification on this? I'd like to make sure I am using the package correctly. Thanks a bunch for all your efforts on the convenience of this package!

**Comment by Russel88** [comment]
Hi teyden

I can understand why you get confused. What I mean by absolute abundances are actual absolute abundances. They are not technically impossible if you have external data, such as qPCR or flow cytometry counts. To me it is confusing to call the raw counts absolute abundances, because they are still relative, even though not being normalised or scaled.

So when relative=TRUE DAtest is normalizing/scaling data internally, so raw counts are expected. When relative=FALSE there is no normalization/scaling internally, so absolute abundances, in the true sense, or pre-normalized data is expected.

I hope it makes sense. 

Cheers,
Jakob

**Comment by teyden** [comment]
Hi Jakob,

Ah, that makes sense, then. Thanks for clarifying!
