### ISSUE TITLE
Phylum level - warning

### ISSUE THREAD

**Issue by miakeady** [Russel88/DAtest#18]
Hello, 

I want to test the difference between two species at the Phylum level. Based on their relative abundance plots, I do not expect them to be different. When I try to run DA test at the phylum level I get the following error:

Set to spike all features. Can't calculate FPR or AUC. Change k argument
In addition: Warning message:
In testDA(p1, predictor = "Species") : Dataset contains very few features

If I try this at Class or a different taxonomic level, I don't get the error. Should I assume there aren't differences at the Phylum level?

Thank you,
Mia

**Comment by Russel88** [comment]
Hi Mia,

The warning does not tell you whether or not there are any differences between the phyla. The problem is that testDA needs enough features (here phyla) to actually compare the different DA methods. With very few features the DA methods cannot be reliably compared.

You could run allDA and compare the results of the different methods:
`test_all <- allDA(p1, predictor = "Species")`
`test_all$adj`
`test_all$est`

or simply choose a DA method that usually works well and go with that, such as DA.wil, DA.ds2, or DA.msf

Regards,
Jakob
